# -*- coding: utf-8 -*-
"""Nombres de rios en espanol, y correcciones al conjunto de datos de origen.

La capa ne_10m_rivers_lake_centerlines de Natural Earth no trae campo name_es:
todos sus nombres estan en la forma local o inglesa. Ademas, unos cuantos
llegan con los caracteres no ASCII comidos ("Rhne" por Rhone, "Gta lv" por
Gota alv, "Ro Grande de Santiago", "Pnuco", "Kiz?lirmak").

Esta tabla arregla las dos cosas. La clave es el nombre tal cual viene en el
dataset; el valor, como debe leerse en un atlas en espanol. Los rios cuyo
nombre es igual en espanol —Congo, Parana, Volga, Amur, Orinoco...— no
aparecen aqui: se dejan tal cual.
"""

NOMBRES_RIOS = {
    # --- nombres rotos en el origen -----------------------------------
    "Kiz?lirmak": "Kizilirmak",
    "Rhne": "Ródano",
    "Gta lv": "Göta älv",
    "Ro Grande de Santiago": "Río Grande de Santiago",
    "Ro Grande de Matagalpa": "Río Grande de Matagalpa",
    "Zncara": "Záncara",
    "Chirrip del Atlntico": "Chirripó del Atlántico",
    "Motala strm": "Motala ström",
    "Santa Mara": "Santa María",
    "Pnuco": "Pánuco",
    "Godävari": "Godavari",
    "Mahäna Nadï": "Mahanadi",
    "Amu  Darya": "Amu Daria",
    "Syr  Darya": "Sir Daria",
    "Sao  Francisco": "São Francisco",
    "São  Francisco": "São Francisco",
    "Bahr el  Zeraf": "Bahr el Zeraf",

    # --- exonimos espanoles: Europa -----------------------------------
    "Danube": "Danubio",
    "Donau": "Danubio",
    "Dunav": "Danubio",
    "Dunarea": "Danubio",
    "Rhine": "Rin",
    "Rhein": "Rin",
    "Rhin": "Rin",
    "Rijn": "Rin",
    "Nederrijn": "Bajo Rin",
    "Waal": "Waal",
    "Thames": "Támesis",
    "Seine": "Sena",
    "Loire": "Loira",
    "Rhône": "Ródano",
    "Rhone": "Ródano",
    "Garonne": "Garona",
    "Elbe": "Elba",
    "Labe": "Elba",
    "Oder": "Óder",
    "Odra": "Óder",
    "Vistula": "Vístula",
    "Wisla": "Vístula",
    "Tejo": "Tajo",
    "Tagus": "Tajo",
    "Douro": "Duero",
    "Guadiana": "Guadiana",
    "Meuse": "Mosa",
    "Maas": "Mosa",
    "Moselle": "Mosela",
    "Mosel": "Mosela",
    "Main": "Meno",
    "Weser": "Weser",
    "Ems": "Ems",
    "Scheldt": "Escalda",
    "Schelde": "Escalda",
    "Tiber": "Tíber",
    "Tevere": "Tíber",
    "Arno": "Arno",
    "Drau": "Drava",
    "Drava": "Drava",
    "Mur": "Mura",
    "Tisa": "Tisza",
    "Sava": "Sava",
    "Dniester": "Dniéster",
    "Dnister": "Dniéster",
    "Dnipro": "Dniéper",
    "Dnepre": "Dniéper",
    "Dnieper": "Dniéper",
    "Prut": "Prut",
    "Siret": "Siret",
    "Daugava": "Duina Occidental",
    "Neman": "Niemen",
    "Vuoksi": "Vuoksi",
    "Kemijoki": "Kemijoki",
    "Glomma": "Glomma",
    "Shannon": "Shannon",
    "Severn": "Severn",
    "Trent": "Trent",
    "Clyde": "Clyde",

    # --- Rusia y Asia septentrional ------------------------------------
    "Ob": "Obi",
    "Irtysh": "Irtish",
    "Ertis": "Irtish",
    "Ertix": "Irtish",
    "Yenisey": "Yeniséi",
    "Verkhniy Yenisey": "Alto Yeniséi",
    "Malyy Yenisey": "Pequeño Yeniséi",
    "Lower Tunguska": "Tunguska Inferior",
    "Stony Tunguska": "Tunguska Pedregosa",
    "Podkamennaya Tunguska": "Tunguska Pedregosa",
    "Lena": "Lena",
    "Aldan": "Aldán",
    "Vilyuy": "Vilyuy",
    "Kolyma": "Kolimá",
    "Indigirka": "Indigirka",
    "Khatanga": "Jatanga",
    "Kheta": "Jeta",
    "Olenëk": "Olenek",
    "Olenek": "Olenek",
    "Anadyr’": "Anádyr",
    "Anadyr": "Anádyr",
    "Pechora": "Pechora",
    "Severnaya Dvina": "Dvina Septentrional",
    "Sukhona": "Sujona",
    "Vychegda": "Víchegda",
    "Kama": "Kama",
    "Oka": "Oká",
    "Don": "Don",
    "Ural": "Ural",
    "Volga": "Volga",
    "Angara": "Angará",
    "Selenga": "Selengá",
    "Amur": "Amur",
    "Argun’": "Argún",
    "Heilong Jiang": "Amur",
    "Hailar": "Hailar",
    "Ussuri": "Ussuri",
    "Songhua": "Songhua",
    "Tom’": "Tom",
    "Taz": "Taz",
    "Neva": "Nevá",
    "Svir": "Svir",
    "Kem": "Kem",
    "Biya": "Biya",
    "Katun": "Katún",
    "Tobol": "Tobol",
    "Ishim": "Ishim",
    "Kamchatka": "Kamchatka",

    # --- Asia meridional y oriental ------------------------------------
    "Yangtze": "Yangtsé",
    "Chang Jiang": "Yangtsé",
    "Jinsha": "Jinsha",
    "Tongtian": "Tongtian",
    "Tuotuo": "Tuotuo",
    "Huang": "Huang He",
    "Huang He": "Huang He",
    "Xi": "Xi",
    "Xun": "Xun",
    "Hongshui": "Hongshui",
    "Mekong": "Mekong",
    "Lancang": "Lancang",
    "Salween": "Saluén",
    "Nu": "Saluén",
    "Nmai": "Nmai",
    "Ayeyarwady": "Irawadi",
    "Irrawaddy": "Irawadi",
    "Irrawaddy Delta": "Delta del Irawadi",
    "Chao Phraya": "Chao Phraya",
    "Red": "Rojo",
    "Hong": "Río Rojo",
    "Ganges": "Ganges",
    "Ganga": "Ganges",
    "Padma": "Padma",
    "Brahmaputra": "Brahmaputra",
    "Yarlung": "Yarlung Tsangpo",
    "Dihang": "Dihang",
    "Maquan": "Maquan",
    "Yamuna": "Yamuna",
    "Indus": "Indo",
    "Shiquan": "Indo Superior",
    "Chenab": "Chenab",
    "Sutlej": "Sutlej",
    "Jhelum": "Yhelum",
    "Ravi": "Ravi",
    "Narmada": "Narmada",
    "Krishna": "Krisná",
    "Kaveri": "Kaveri",
    "Helmand": "Helmand",
    "Amu Darya": "Amu Daria",
    "Syr Darya": "Sir Daria",
    "Panj": "Panj",
    "Naryn": "Narín",
    "Tarim": "Tarim",
    "Yarkant": "Yarkand",
    "Konqi": "Konqi",
    "Euphrates": "Éufrates",
    "Al Furat": "Éufrates",
    "Firat": "Éufrates",
    "Tigris": "Tigris",
    "Dicle": "Tigris",
    "Shatt al Arab": "Shatt al-Arab",
    "Jordan": "Jordán",
    "Kura": "Kurá",
    "Sakarya": "Sakarya",
    "Ishikari": "Ishikari",
    "Han": "Han",
    "Liao": "Liao",

    # --- Africa ---------------------------------------------------------
    "Nile": "Nilo",
    "El Bahr el Abyad": "Nilo Blanco",
    "El Bahr el Azraq": "Nilo Azul",
    "Victoria Nile": "Nilo Victoria",
    "Albert Nile": "Nilo Alberto",
    "Bahr el Jebel": "Bahr el Yebel",
    "Damietta Branch": "Brazo de Damieta",
    "Rosetta Branch": "Brazo de Roseta",
    "Abay": "Nilo Azul",
    "Atbara": "Atbara",
    "Kagera": "Kagera",
    "Congo": "Congo",
    "Lualaba": "Lualaba",
    "Ubangi": "Ubangui",
    "Uele": "Uele",
    "Kasai": "Kasai",
    "Kwango": "Kwango",
    "Sangha": "Sangha",
    "Niger": "Níger",
    "Benue": "Benue",
    "Bénoué": "Benue",
    "Sénégal": "Senegal",
    "Bafing": "Bafing",
    "Gambia": "Gambia",
    "Volta": "Volta",
    "Mouhoun": "Mouhoun",
    "Nakanbé": "Nakanbé",
    "Chari": "Chari",
    "Zambezi": "Zambeze",
    "Shire": "Shire",
    "Kafue": "Kafue",
    "Limpopo": "Limpopo",
    "Orange": "Orange",
    "Vaal": "Vaal",
    "Okavango": "Okavango",
    "Cubango": "Cubango",
    "Cunene": "Cunene",
    "Ruvuma": "Ruvuma",
    "Jubba": "Yuba",
    "Omo": "Omo",
    "Genale": "Genale",
    "Sanaga": "Sanaga",
    "Sassandra": "Sassandra",
    "Senegal": "Senegal",

    # --- America del Norte ---------------------------------------------
    "Mississippi": "Misisipi",
    "Missouri": "Misuri",
    "Ohio": "Ohio",
    "Allegheny": "Allegheny",
    "Arkansas": "Arkansas",
    "Tennessee": "Tennessee",
    "Rio Grande": "Río Grande",
    "Colorado": "Colorado",
    "Columbia": "Columbia",
    "Snake": "Snake",
    "St. Lawrence": "San Lorenzo",
    "St. Clair": "Santa Clara",
    "Niagara": "Niágara",
    "Mackenzie": "Mackenzie",
    "Peace": "Paz",
    "Slave": "Esclavos",
    "Athabasca": "Athabasca",
    "Saskatchewan": "Saskatchewan",
    "North Saskatchewan": "Saskatchewan Norte",
    "South Saskatchewan": "Saskatchewan Sur",
    "Nelson": "Nelson",
    "Churchill": "Churchill",
    "Yukon": "Yukón",
    "Teslin": "Teslin",
    "Fraser": "Fraser",
    "Liard": "Liard",
    "Ottawa": "Ottawa",
    "R. des Outaouais": "Ottawa",
    "La Grande": "La Grande",
    "Hudson": "Hudson",
    "Potomac": "Potomac",
    "Savannah": "Savannah",
    "Alabama": "Alabama",
    "Brazos": "Brazos",
    "Trinity": "Trinity",
    "Sacramento": "Sacramento",
    "San Joaquin": "San Joaquín",
    "Willamette": "Willamette",
    "Kuskokwim": "Kuskokwim",
    "Susitna": "Susitna",
    "Copper": "Cobre",
    "Coppermine": "Coppermine",
    "Back": "Back",
    "Thelon": "Thelon",
    "Albany": "Albany",
    "Winnipeg": "Winnipeg",
    "Rainy": "Rainy",
    "Usumacinta": "Usumacinta",
    "Coco": "Coco",
    "Chixoy": "Chixoy",
    "Panama Canal": "Canal de Panamá",
    "Suez Canal": "Canal de Suez",
    "Ismailiya Canal": "Canal de Ismailía",
    "Gharraf Canal": "Canal de Gharraf",

    # --- America del Sur ------------------------------------------------
    "Amazonas": "Amazonas",
    "Amazon": "Amazonas",
    "Ucayali": "Ucayali",
    "Marañón": "Marañón",
    "Madeira": "Madeira",
    "Mamoré": "Mamoré",
    "Guaporé": "Guaporé",
    "Beni": "Beni",
    "Madre de Dios": "Madre de Dios",
    "Purús": "Purús",
    "Juruá": "Juruá",
    "Japurá": "Yapurá",
    "Caquetá": "Caquetá",
    "Negro": "Negro",
    "Branco": "Branco",
    "Xingu": "Xingú",
    "Tapajós": "Tapajós",
    "Juruena": "Juruena",
    "Teles Pires": "Teles Pires",
    "Tocantins": "Tocantins",
    "Araguaia": "Araguaia",
    "Paranaíba": "Paranaíba",
    "Paraná": "Paraná",
    "Paraguay": "Paraguay",
    "Uruguay": "Uruguay",
    "Pilcomayo": "Pilcomayo",
    "Bermejo": "Bermejo",
    "Salado": "Salado",
    "Orinoco": "Orinoco",
    "Meta": "Meta",
    "Magdalena": "Magdalena",
    "Cauca": "Cauca",
    "Putumayo": "Putumayo",
    "Bío-Bío": "Biobío",
    "Neuquén": "Neuquén",
    "Chubut": "Chubut",
    "Santa Cruz": "Santa Cruz",
    "Desaguadero": "Desaguadero",
    "Mendoza": "Mendoza",
    "Jequitinhonha": "Jequitinhonha",
    "Paraiba": "Paraíba",

    # --- Oceania ---------------------------------------------------------
    "Murray": "Murray",
    "Darling": "Darling",
    "Barwon": "Barwon",
    "Lachlan": "Lachlan",
    "Fitzroy": "Fitzroy",
    "Ord": "Ord",
    "Daly": "Daly",
    "Mitchell": "Mitchell",
    "Waikato": "Waikato",
    "Clutha": "Clutha",
    "Purari": "Purari",
    "Sepik": "Sepik",
    "Fly": "Fly",
    "Digul": "Digul",
    "Mamberamo": "Mamberamo",
    "Kapuas": "Kapuas",
    "Barito": "Barito",
    "Kayan": "Kayan",
}
