# -*- coding: utf-8 -*-
"""Nombres en espanol de los 180 paises del dataset.

La clave es el nombre en ingles tal y como aparece en countries.geo.json.
build_data.py falla si algun pais del origen no esta aqui, para que una
actualizacion del dataset no se cuele con la etiqueta en ingles.
"""

NOMBRES = {
    "Afghanistan": "Afganistán",
    "Albania": "Albania",
    "Algeria": "Argelia",
    "Angola": "Angola",
    "Antarctica": "Antártida",
    "Argentina": "Argentina",
    "Armenia": "Armenia",
    "Australia": "Australia",
    "Austria": "Austria",
    "Azerbaijan": "Azerbaiyán",
    "Bangladesh": "Bangladés",
    "Belarus": "Bielorrusia",
    "Belgium": "Bélgica",
    "Belize": "Belice",
    "Benin": "Benín",
    "Bermuda": "Bermudas",
    "Bhutan": "Bután",
    "Bolivia": "Bolivia",
    "Bosnia and Herzegovina": "Bosnia y Herzegovina",
    "Botswana": "Botsuana",
    "Brazil": "Brasil",
    "Brunei": "Brunéi",
    "Bulgaria": "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    "Burundi": "Burundi",
    "Cambodia": "Camboya",
    "Cameroon": "Camerún",
    "Canada": "Canadá",
    "Central African Republic": "República Centroafricana",
    "Chad": "Chad",
    "Chile": "Chile",
    "China": "China",
    "Colombia": "Colombia",
    "Costa Rica": "Costa Rica",
    "Croatia": "Croacia",
    "Cuba": "Cuba",
    "Cyprus": "Chipre",
    "Czech Republic": "Chequia",
    "Democratic Republic of the Congo": "República Democrática del Congo",
    "Denmark": "Dinamarca",
    "Djibouti": "Yibuti",
    "Dominican Republic": "República Dominicana",
    "East Timor": "Timor Oriental",
    "Ecuador": "Ecuador",
    "Egypt": "Egipto",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Guinea Ecuatorial",
    "Eritrea": "Eritrea",
    "Estonia": "Estonia",
    "Ethiopia": "Etiopía",
    "Falkland Islands": "Islas Malvinas",
    "Fiji": "Fiyi",
    "Finland": "Finlandia",
    "France": "Francia",
    "French Guiana": "Guayana Francesa",
    "French Southern and Antarctic Lands": "Tierras Australes Francesas",
    "Gabon": "Gabón",
    "Gambia": "Gambia",
    "Georgia": "Georgia",
    "Germany": "Alemania",
    "Ghana": "Ghana",
    "Greece": "Grecia",
    "Greenland": "Groenlandia",
    "Guatemala": "Guatemala",
    "Guinea": "Guinea",
    "Guinea Bissau": "Guinea-Bisáu",
    "Guyana": "Guyana",
    "Haiti": "Haití",
    "Honduras": "Honduras",
    "Hungary": "Hungría",
    "Iceland": "Islandia",
    "India": "India",
    "Indonesia": "Indonesia",
    "Iran": "Irán",
    "Iraq": "Irak",
    "Ireland": "Irlanda",
    "Israel": "Israel",
    "Italy": "Italia",
    "Ivory Coast": "Costa de Marfil",
    "Jamaica": "Jamaica",
    "Japan": "Japón",
    "Jordan": "Jordania",
    "Kazakhstan": "Kazajistán",
    "Kenya": "Kenia",
    "Kosovo": "Kosovo",
    "Kuwait": "Kuwait",
    "Kyrgyzstan": "Kirguistán",
    "Laos": "Laos",
    "Latvia": "Letonia",
    "Lebanon": "Líbano",
    "Lesotho": "Lesoto",
    "Liberia": "Liberia",
    "Libya": "Libia",
    "Lithuania": "Lituania",
    "Luxembourg": "Luxemburgo",
    "Macedonia": "Macedonia del Norte",
    "Madagascar": "Madagascar",
    "Malawi": "Malaui",
    "Malaysia": "Malasia",
    "Mali": "Malí",
    "Malta": "Malta",
    "Mauritania": "Mauritania",
    "Mexico": "México",
    "Moldova": "Moldavia",
    "Mongolia": "Mongolia",
    "Montenegro": "Montenegro",
    "Morocco": "Marruecos",
    "Mozambique": "Mozambique",
    "Myanmar": "Birmania",
    "Namibia": "Namibia",
    "Nepal": "Nepal",
    "Netherlands": "Países Bajos",
    "New Caledonia": "Nueva Caledonia",
    "New Zealand": "Nueva Zelanda",
    "Nicaragua": "Nicaragua",
    "Niger": "Níger",
    "Nigeria": "Nigeria",
    "North Korea": "Corea del Norte",
    "Northern Cyprus": "Chipre del Norte",
    "Norway": "Noruega",
    "Oman": "Omán",
    "Pakistan": "Pakistán",
    "Panama": "Panamá",
    "Papua New Guinea": "Papúa Nueva Guinea",
    "Paraguay": "Paraguay",
    "Peru": "Perú",
    "Philippines": "Filipinas",
    "Poland": "Polonia",
    "Portugal": "Portugal",
    "Puerto Rico": "Puerto Rico",
    "Qatar": "Catar",
    "Republic of Serbia": "Serbia",
    "Republic of the Congo": "República del Congo",
    "Romania": "Rumanía",
    "Russia": "Rusia",
    "Rwanda": "Ruanda",
    "Saudi Arabia": "Arabia Saudí",
    "Senegal": "Senegal",
    "Sierra Leone": "Sierra Leona",
    "Slovakia": "Eslovaquia",
    "Slovenia": "Eslovenia",
    "Solomon Islands": "Islas Salomón",
    "Somalia": "Somalia",
    "Somaliland": "Somalilandia",
    "South Africa": "Sudáfrica",
    "South Korea": "Corea del Sur",
    "South Sudan": "Sudán del Sur",
    "Spain": "España",
    "Sri Lanka": "Sri Lanka",
    "Sudan": "Sudán",
    "Suriname": "Surinam",
    "Swaziland": "Esuatini",
    "Sweden": "Suecia",
    "Switzerland": "Suiza",
    "Syria": "Siria",
    "Taiwan": "Taiwán",
    "Tajikistan": "Tayikistán",
    "Thailand": "Tailandia",
    "The Bahamas": "Bahamas",
    "Togo": "Togo",
    "Trinidad and Tobago": "Trinidad y Tobago",
    "Tunisia": "Túnez",
    "Turkey": "Turquía",
    "Turkmenistan": "Turkmenistán",
    "Uganda": "Uganda",
    "Ukraine": "Ucrania",
    "United Arab Emirates": "Emiratos Árabes Unidos",
    "United Kingdom": "Reino Unido",
    "United Republic of Tanzania": "Tanzania",
    "United States of America": "Estados Unidos",
    "Uruguay": "Uruguay",
    "Uzbekistan": "Uzbekistán",
    "Vanuatu": "Vanuatu",
    "Venezuela": "Venezuela",
    "Vietnam": "Vietnam",
    "West Bank": "Cisjordania",
    "Western Sahara": "Sáhara Occidental",
    "Yemen": "Yemen",
    "Zambia": "Zambia",
    "Zimbabwe": "Zimbabue",
}


# Paises que aparecen en el nivel administrativo 1 de Natural Earth pero no
# en el mapa de 180 paises: territorios y microestados.
PAISES_NE = {
    'Akrotiri Sovereign Base Area': 'Acrotiri',
    'Aland': 'Åland',
    'American Samoa': 'Samoa Americana',
    'Andorra': 'Andorra',
    'Anguilla': 'Anguila',
    'Antigua and Barbuda': 'Antigua y Barbuda',
    'Ashmore and Cartier Islands': 'Islas Ashmore y Cartier',
    'Bermuda': 'Bermudas',
    'Clipperton Island': 'Isla Clipperton',
    'Monaco': 'Mónaco',
    'Nauru': 'Nauru',
    'San Marino': 'San Marino',
    'Spratly Is.': 'Islas Spratly',
    'United States Minor Outlying Islands': 'Islas Menores de EE. UU.',
    'Aruba': 'Aruba',
    'Bahrain': 'Baréin',
    'Barbados': 'Barbados',
    'Baykonur Cosmodrome': 'Cosmódromo de Baikonur',
    'British Indian Ocean Territory': 'Territorio Británico del Océano Índico',
    'British Virgin Islands': 'Islas Vírgenes Británicas',
    'Cape Verde': 'Cabo Verde',
    'Cayman Islands': 'Islas Caimán',
    'Comoros': 'Comoras',
    'Cook Islands': 'Islas Cook',
    'Curaçao': 'Curazao',
    'Dhekelia Sovereign Base Area': 'Dhekelia',
    'Dominica': 'Dominica',
    'Faroe Islands': 'Islas Feroe',
    'Federated States of Micronesia': 'Micronesia',
    'French Polynesia': 'Polinesia Francesa',
    'Gaza Strip': 'Franja de Gaza',
    'Grenada': 'Granada',
    'Guam': 'Guam',
    'Guernsey': 'Guernsey',
    'Heard Island and McDonald Islands': 'Islas Heard y McDonald',
    'Hong Kong S.A.R.': 'Hong Kong',
    'Indian Ocean Territories': 'Territorios del Océano Índico',
    'Isle of Man': 'Isla de Man',
    'Jersey': 'Jersey',
    'Kiribati': 'Kiribati',
    'Liechtenstein': 'Liechtenstein',
    'Macao S.A.R': 'Macao',
    'Marshall Islands': 'Islas Marshall',
    'Mauritius': 'Mauricio',
    'Montserrat': 'Montserrat',
    'Niue': 'Niue',
    'Norfolk Island': 'Isla Norfolk',
    'Northern Mariana Islands': 'Islas Marianas del Norte',
    'Palau': 'Palaos',
    'Pitcairn Islands': 'Islas Pitcairn',
    'Saint Helena': 'Santa Elena',
    'Saint Kitts and Nevis': 'San Cristóbal y Nieves',
    'Saint Lucia': 'Santa Lucía',
    'Saint Martin': 'San Martín',
    'Saint Pierre and Miquelon': 'San Pedro y Miquelón',
    'Saint Vincent and the Grenadines': 'San Vicente y las Granadinas',
    'Samoa': 'Samoa',
    'Sao Tome and Principe': 'Santo Tomé y Príncipe',
    'Seychelles': 'Seychelles',
    'Siachen Glacier': 'Glaciar de Siachen',
    'Singapore': 'Singapur',
    'South Georgia and the Islands': 'Georgia del Sur y Sandwich del Sur',
    'Tonga': 'Tonga',
    'Turks and Caicos Islands': 'Islas Turcas y Caicos',
    'Tuvalu': 'Tuvalu',
    'US Naval Base Guantanamo Bay': 'Base Naval de Guantánamo',
    'United States Virgin Islands': 'Islas Vírgenes de EE. UU.',
    'Wallis and Futuna': 'Wallis y Futuna',
}

# Nombres que Natural Earth escribe distinto al mapa de paises.
ALIAS_NE = {
    'Czechia': 'Czech Republic',
    'Macedonia': 'Macedonia',
    'Republic of Serbia': 'Republic of Serbia',
    'Republic of the Congo': 'Republic of the Congo',
    'S. Sudan': 'South Sudan',
    'The Bahamas': 'The Bahamas',
    'Timor-Leste': 'East Timor',
    'Vatican': 'Vatican',
    'eSwatini': 'Swaziland',
}
